require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions:
    rubocop-rake: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Metrics/MethodLength:
  Max: 20
