require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions:
    rubocop-rake: false
  Exclude:
    - "db/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Metrics/MethodLength:
  Max: 20
RSpec/MessageChain:
  Enabled: false
RSpec/ExampleLength:
  Max: 50
RSpec/MultipleExpectations:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
