version: "3.9"
services:
  library:
    platform: linux/x86_64
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ".:/library"
      - bundle:/bundle
volumes:
  bundle:
