name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run Rubocop
        run: |
          bundle exec rubocop
      - name: Run tests
        run: |
          bundle exec rake
